export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf9f8",
        "inverse-surface": "#303030",
        "on-primary-fixed-variant": "#00468b",
        "on-tertiary-fixed": "#00201b",
        "surface-tint": "#005db5",
        "surface-container": "#efeded",
        "secondary-fixed": "#cbe6ff",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        "on-primary-container": "#cadcff",
        "tertiary-fixed-dim": "#83d5c5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4e677c",
        "tertiary-fixed": "#9ff2e1",
        "surface-dim": "#dbdad9",
        "on-tertiary-container": "#97ead9",
        "error-container": "#ffdad6",
        "primary-fixed": "#d6e3ff",
        "secondary-container": "#cbe6ff",
        "outline": "#727783",
        "tertiary": "#005247",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface": "#fbf9f8",
        "on-error": "#ffffff",
        "tertiary-container": "#036c5f",
        "primary-container": "#005fb8",
        "on-secondary-fixed": "#001e30",
        "secondary": "#486176",
        "surface-container-low": "#f5f3f3",
        "inverse-on-surface": "#f2f0f0",
        "on-surface-variant": "#424752",
        "on-primary-fixed": "#001b3d",
        "secondary-fixed-dim": "#afcae2",
        "primary": "#00488d",
        "outline-variant": "#c2c6d4",
        "on-tertiary-fixed-variant": "#005046",
        "on-secondary-fixed-variant": "#30495d",
        "surface-container-highest": "#e4e2e2",
        "primary-fixed-dim": "#a8c8ff",
        "on-surface": "#1b1c1c",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1c1c",
        "background": "#fbf9f8",
        "inverse-primary": "#a8c8ff",
        "surface-variant": "#e4e2e2"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
